### ISSUE TITLE
Middleman support?

### ISSUE THREAD

**Issue by skatkov** [styd/apexcharts.rb#15]
**Is your feature request related to a problem? Please describe.**
I'd love to use this library with a middleman framework.
https://middlemanapp.com/

**Describe the solution you'd like**
I've managed to get it running with my existing middleman project, just had to do a little bit more plumbing code.

in config.rb I've added
`helpers ApexCharts::Helper`
And by explicitly adding apexchart.js library into view.

I don't think that it's possible to make a loader for gem. yeat, maybe we can update README to help offers get started faster?

**Comment by styd** [comment]
@skatkov, I'm not familiar with middleman. If you don't mind, can you make a pull request for adding middleman in the web support section on README. That would be really helpful for other people using middleman.

**Comment by styd** [comment]
[Middleman is supported now.](https://a-styd.gitbook.io/apexcharts-ruby/miscellaneous/web-support/middleman)
It will be available in next release. Or you can get it from `master` branch now:
```ruby
gem 'apexcharts', github: 'styd/apexcharts.rb'
```
