### ISSUE TITLE
[BUG] Color pallete is not sufficient for big datasets

### ISSUE THREAD

**Issue by skatkov** [styd/apexcharts.rb#16]
**Describe the bug**
Check out charts i've built:
https://fbacatalog.com/charts/trial.html
There are a lot of datapoints -- 10 to be precise. And some of the colors are repeating, so  it's really hard to understand what part of chart is related to certain data point.

**Expected behavior**
I'd expect that every data point should have it's own color. Then it would be easier to understand this chart.

**Screenshots**
<img width="727" alt="Screenshot 2019-07-22 at 17 19 26" src="https://user-images.githubusercontent.com/544377/61626181-c9b2d600-aca6-11e9-8d3d-a6b3a76c288e.png">

**Comment by styd** [comment]
Unfortunately, ApexCharts does not pick random colors for each series. Instead it defines 10 palettes of 5 colors each ready to use as given [here](https://apexcharts.com/docs/options/theme/). So, for your case, I guess you're going to have to specify each color and make sure they are different yourself by specifying the options for `colors`, e.g.:
```ruby
colors: ['#00FFFF', '#5F9EA0', '#7FFF00', '#FF7F50', '#DC143C', '#008B8B', '#00CED1', '#9400D3', '#FF1493', '#00BFFF', '#1E90FF', '#B22222']
```
In the next version, you can define your own reusable custom theme palettes and use it anywhere as easy as setting `theme: 'my_palette'`. But, for now, please try the `colors` options above.

Let me know if this work for you.

**Comment by styd** [comment]
The current version (v0.1.6) supports creating your own custom palette. Although it doesn't create palette colors automatically, you can specify as many as you need. So I'm closing this issue.
