### ISSUE TITLE
[BUG] Issues with installation on Rails project

### ISSUE THREAD

**Issue by daveomcd** [styd/apexcharts.rb#21]
I'm attempting to try this gem out with my Rails project.  I'm attempting install on a Rail 5.1.6 app.  I'm getting errors with the `<% include ApexCharts::Helper %>` line as I'm receiving the error: "undefined method `include' for #<#<Class:0x00007fffdaa9a1c8>:0x00007f83495673f8>".

**To Reproduce**
1. Added the two gems 'apexcharts' and 'groupdate'
2. bundle install
3. Added **//= require 'apexcharts'** to my _/assets/javascripts/application.js_ file
4. Created **/application/_apex_charts.html.erb** partial to keep the following lines in...

`<script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
<% require 'set' %>
<% require 'apexcharts' %>
<% include ApexCharts::Helper %>`

5. Create another partial with the following inside...

`<%= render partial: "apex_charts" %>

<% series = [
  { name: "Weigh (In)", data: @player.body_weight_recordings.ordered.pluck(:weigh_in_value) },
  { name: "Weigh (Out)", data: @player.body_weight_recordings.ordered.pluck(:weigh_out_value) }] 
%>

<%= options = {
  title: "Weight History",
  subtitle: "Example Subtitle",
  xtitle: 'Week',
  ytitle: 'Weight',
  stacked: true
} %>

<%= line_chart(series, options) %>`

6. Load webpage and get the error mentioned above.

**Expected behavior**
I expected my code to break :)

**Comment by styd** [comment]
Hi, @daveomcd. Thank you for reporting this issue.
I see that you are following both instruction for Rails and for Plain HTML+ERB.
They are actually separated things.

If you're using Rails, you should only follow the instruction for Rails even if you're using `.erb` files.
The HTML+ERB instruction is meant for plain `.erb` file without framework. The one that you generate with `erb sample.html.erb > sample.html` and then open the sample.html as a static web page. I should've written the instruction more clearly.

Can you try again by following just the instruction for Rails? I, myself, have been using this gem for months in a Rails app (without webpacker), and have no problem installing and using it with the instruction for Rails. But, I understand that different project has different setups, therefore different problems. I appreciate it if you come back again after trying only the instruction for Rails app.
Thank you for trying this gem.

**Comment by daveomcd** [comment]
Thanks @styd, I knew I was doing something stupid!  I appreciate the work, and the help in understanding this.  Thanks again!

**Comment by styd** [comment]
No problem. So, I assume this has been solved. If you face another issue please don't hesitate to post it as a new issue. Thanks.
