### ISSUE TITLE
Undefined method error for empty series

### ISSUE THREAD

**Issue by irwalker** [styd/apexcharts.rb#41]
Thanks for this excellent gem @styd .

When loading a chart with an empty series, you will encounter the following error:
    undefined method `[]' for nil:NilClass

#### Reproduce the bug

For example:
    <%= column_chart([], {
        title: 'My graph',
        xtitle: 'Horizontal Series',
        ytitle: 'Vertical Series',
        theme: 'mytheme' }) %>

#### Expected Behaviour

I would have expected an empty series to show an empty graph.

#### Actual behaviour

![Screenshot 2019-09-23 at 16 06 49](https://user-images.githubusercontent.com/2808271/65437778-52bbca00-de1c-11e9-8f2c-84fb37d93595.png)

#### Stack trace

![Screenshot 2019-09-23 at 16 07 40](https://user-images.githubusercontent.com/2808271/65437799-5a7b6e80-de1c-11e9-9e3b-84c7595cbd1b.png)

**Comment by styd** [comment]
Hi, @irwalker, thanks for using this gem.

This seems like a valid bug 'cause I don't recall handling empty series. Haven't check the code yet.

I'll check and fix it soon. But if you know how to fix it, PR is very much welcomed.

**Comment by irwalker** [comment]
I've had a go at raising a PR to fix this, would be keen to hear your thoughts. Cheers

**Comment by styd** [comment]
Fixed by #42.
