### ISSUE TITLE
[BUG] uninitialized constant ApexCharts::Helper::MixedCharts

### ISSUE THREAD

**Issue by lepepe** [styd/apexcharts.rb#49]
When trying to use combo/mixed chart I'm getting the following error:
![Screen Shot 2019-10-30 at 4 06 59 PM](https://user-images.githubusercontent.com/12739553/67894654-59321580-fb2f-11e9-9fc4-b94aae1cc72f.png)

#### Application js:
```
//= require apexcharts
```

#### Gemfile:
```
gem 'apexcharts', require: 'apexcharts/prefix_with_apex'
```
#### erb:
```
<%= apex_combo_charts({**options, theme: 'palette4', stacked: false, data_labels: false}) do %>
  <% line_chart(serie_one) %>
  <% column_chart(serie_two) %>
<% end %>
```

I'm using Rails 5.1.6.

**Comment by styd** [comment]
Thanks for reporting the issue. I just realized many other bugs while trying to fix this.
