### ISSUE TITLE
How can we add some events for chart?

### ISSUE THREAD

**Issue by ammar299** [styd/apexcharts.rb#57]
I can't able to find something that help me to add event for chart like there official document defined.
![image](https://user-images.githubusercontent.com/43796948/78547806-1a5c6600-7819-11ea-974b-befe8bc7075a.png)

How can I add some events like this into my project. Here is my code for option.

`<% bubble_series = @prob_array.each_with_index.map do |prob,i|
 {
    name: "Bubble #{i}",
    data: [[i+1,rand(10..50), prob , rand(10..500)]],
  }
  end %>
  <% options = {
    xtitle: 'bubble number',
    ytitle: 'bubble ',
    height: 500,
    # data_labels: false, 
    theme: 'palette6',
    
    chart: {
      events: {
        dataPointSelection: function(event, chartContext, config) {
        console.log(event, chartContext, config);
       }
     },
     toolbar: {
       show: false
     }
    },
    } %>`

This giving me an error 

![image](https://user-images.githubusercontent.com/43796948/78549204-6f00e080-781b-11ea-843b-423330e5547c.png)

**Comment by styd** [comment]
You can't call a `function` in Ruby the JavaScript way. If you still wanna do so, you can try using [functionable-json](https://github.com/styd/functionable-json) as mentioned in readme: https://github.com/styd/apexcharts.rb#formatter-function. But even so, you still need to initialize your variable:
```
event, chartContext, config = nil
...
chart: {
  events: {
    dataPointSelection: function(event, chartContext, config) {
    console.log(event, chartContext, config);
  }
},
...
```
Another option is to use function as object:
```
chart: {
  events: {
    dataPointSelection: function: {
      args: "event,chartContext,config",
      body: "console.log(event, chartContext, config);"
    }
  }
},
...
```
Tell me if either of these options work for you.

**Comment by ammar299** [comment]
thanks ......this work for me.....
chart: {
  events: {
    dataPointSelection: {
      function: {
        args: "event,chartContext,config",
        body: "console.log(event, chartContext, config);"
      }
    }
  }
},

**Comment by styd** [comment]
I'm glad that it works for you.

**Comment by ammar299** [comment]
> I'm glad that it works for you.

nope its not working. because i cant see result when i click...

**Comment by styd** [comment]
Can you open web inspector on that page and tell me if you see your function like this:
```
function(event, chartContext, config) {
   console.log(event, chartContext, config);
}
```
If you see it and still doesn't work, then it's ApexCharts.JS bug.

**Comment by ammar299** [comment]
![image](https://user-images.githubusercontent.com/43796948/79573709-7d32e480-80d8-11ea-94a4-c9cf52e7a3ce.png)
i can see this......

**Comment by styd** [comment]
Which version of ApexCharts.RB are you using?
