### ISSUE TITLE
Heatmap shading options

### ISSUE THREAD

**Issue by nickseferos** [styd/apexcharts.rb#59]
I am working on a project requiring heatmaps with largely varying data. I am trying to either: 
1) utilize the distributed option as described in apexcharts docs`options = { plotOptions: { heatmap: { distributed: true }}}`
or 2) disable shading entirely

When I use these options, I am returned with this `unrecognized key: :distributed in ApexCharts::Options::RootOptions`

Am I either missing something with this option or is it not available to use for heatmaps?

Thanks in advance

**Comment by styd** [comment]
Hi, sorry for a late response.
`RootOptions` shouldn't care about `plotOptions` options, so it should work fine.
I've tried your options to my multiple rows heatmap chart, and it didn't raise any error.
Although, I don't know what it does, since nothing on the chart changed in my case.
Can you provide in more detail how you used the options?

**Comment by nickseferos** [comment]
Now it'd my turn to apologize for an extremely late response.

Rendered that chart displays like this:
![Screen Shot 2020-07-06 at 2 22 55 PM](https://user-images.githubusercontent.com/12157400/86647244-c0447b80-bf94-11ea-9fba-2ee58fc46516.png)

and does not let a user easily see a smaller value for the lower average valued rows.


In my helper for the heatmap I have:
```
def yard_heatmap_options
    { title: 'Average Transactions by Day of the Week', xtitle: 'Day of the Week', animations: false, options: { plotOptions: { heatmap: { distributed: true }}} }
end
```
but that returns
```
unrecognized key: :options in ApexCharts::Options::RootOptions.
```
Again, it may be a case of not really understanding how to use the options (or not reading the documentation clearly).

Thanks again.

**Comment by styd** [comment]
Sorry for another late response. I had measles since last week.
Your intuition was right. `plotOptions` should be at the same level as `title` and `animations`.
