### ISSUE TITLE
[BUG] dataLabels background option not working

### ISSUE THREAD

**Issue by alliedarmour** [styd/apexcharts.rb#60]
**Describe the bug**
I wanted to set some background options for my dataLabels and encountered the problem, that the background option can't be used.

That's the code:

```
<%= line_chart(
    [{ name: "Bewertung", data: Feedback.group_by_week(:date, format: "%d.%m.%Y", last: 4).average(:overall_impression_feed)}], 
    dataLabels: {  
        enabled: true,
        formatter: { function: { args: "value", body: "return value.toFixed(2);" } },
        style: {
            fontSize: "12px"
        },
        background: { 
            enabled: true
         }
    },
    title: "Bewertung allgemeine Zufriedenheit",
    subtitle: "Wochenübersicht",
    xtitle: "Kalenderwoche",
    ytitle: "Durchschnittsbewertung",
    animations: true,
    tooltip: true,
    chart: { width: "100%", height: "500px" },
    yaxis: { min: 1, max: 5, tickAmount: 5, decimalsInFloat: 1, forceNiceScale: true }) do %> 

    <% y_annotation(value: (0.0 .. 2.0), text: "", color: "green") %>
    <% y_annotation(value: (2.0 .. 4.0), text: "", color: "orange") %>
    <% y_annotation(value: (4.0 .. 5.0), text: "", color: "red") %>

<% end %>

```

**Screenshots**
![apex-error](https://user-images.githubusercontent.com/20596363/84603216-f490b480-ae8c-11ea-8468-80954bfa28dd.png)

Couldn't find anything about passing additional options to the dataLabels in dhe docs.

But nevertheless thanks for this amazing gem!

**Comment by styd** [comment]
Hi, @alliedarmour . Sorry for a late response. `background` option for dataLabels was added after the last release (v0.1.9).
If you're not using the master branch, please use it for the time being.

**Comment by styd** [comment]
Hi, @alliedarmour . Please upgrade to the latest version and tell me if the bug still happens.

**Comment by alliedarmour** [comment]
Hello, sorry for my late answer aswell! I can confirm it's working in development and on production! Thanks for the hint!
