### ISSUE TITLE
[BUG] Duplicating charts when going back to the chart page

### ISSUE THREAD

**Issue by marcelolx** [styd/apexcharts.rb#65]
**Describe the bug**
When i'm on the chart page and go to another by a link for example and go back to the page the charts are being duplicated.

I'm not sure if I missing something, but I haven't found anything related to this.

**To Reproduce**
I created a sample repo https://github.com/marcelolx/apexcharts-test

But basically is 
- adding the gem and the yarn package to the project
- add two pages, one to chart and another to go through a link for example
- run the project, go to the chart page -> go to the another page -> go back to the chart page through navigator backward button.

**Expected behavior**
Doesn't duplicate de chart.

**Screenshots**
![apexcharts bug](https://user-images.githubusercontent.com/20196775/94264732-9b193680-ff0d-11ea-996a-f29919453cb6.gif)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [Chrome - 85.0.4183.121]

**Comment by styd** [comment]
Hi, @marcelolx . Sorry for a late response.
I believe this is a turbolinks issue. I've confirmed it by disabling turbolinks on your sample repo and the duplication no longer occurs.
You can read [similar issue on turbolinks repo](https://github.com/turbolinks/turbolinks/issues/106).
